---
title: "My Academic/Professional Experience (aka my CV)"
output: 
  html_document:
    toc: true
    toc_float: true
---

## EDUCATION AND TRAINING
2018-present	Columbia University, New York, NY  
NLM Postdoctoral Fellow, Department of Biomedical Informatics

2014-2017	University of California San Francisco, San Francisco, CA  
Internship and Residency, Department of Medicine

2009-2014	Yale School of Medicine, New Haven, CT  
Doctor of Medicine

2005-2009	Duke University, Durham, NC  
B.A. in Computer Science; Minors in Biology, Chemistry

### ACADEMIC/PROFESSIONAL POSITIONS AND APPOINTMENTS
2017-present	Weill Cornell College of Medicine/New York-Presbyterian Hospital, New York, NY  
Clinical Assistant Professor/Attending Physician, Division of Hospital Medicine, Department of Medicine

2017-2018	Columbia University Medical Center, New York, NY  
Postdoctoral Research Scientist, Department of Biomedical Informatics

### BOARD CERTIFICATION
American Board of  Internal Medicine

### MEDICAL LICENSURE
New York #288983

### AWARDS/HONORS
2018-present	NIH/NLM T15 Training Grant—University-based Biomedical Informatics and Data Science Research Training Program
2018	Distinguished Poster Award, AMIA 2018 Annual Symposium
2016		UCSF Department of Medicine Tech Challenge Winner
2016		UCSF Education Innovations Funding Grant Recipient
2012-2013	James G. Hirsch, M.D., Endowed Medical Student Research Fellowship
2012		Yale Entrepreneurial Institute Summer Fellowship Finalist- ASSESS Systems
2011	American Pediatric Society/Society for Pediatric Research- Travel Award for PAS 2011

### EDITORIAL BOARDS
2012-2014	Circulation: Cardiovascular Quality and Outcomes (Section Editor)

### PUBLICATIONS
Suchard MA, Schuemie MJ, Krumholz HM, You SC, **Chen R**, Pratt N, Reich CG, Duke J, Madigan D, Hripcsak G, Ryan PB. Comprehensive comparative effectiveness and safety of first-line antihypertensive drug classes: a systematic, multinational, large-scale analysis. The Lancet. 2019.

**Chen R**, Falconer T, Hripcsak G. Feasibility of Large-Scale Observational Cancer Research using the OHDSI Network White Paper. National Cancer Institute, 2018. 

**Chen R**, Scherzer R, Hsue PY, Jotwani V, Estrella MM, Horberg MA, Grunfeld C, Shlipak MG. Association of Tenofovir Use with Risk of Incident Heart Failure in HIV-infected Patients. J Am Heart Assoc. 2017;6.

**Chen R**, Desai NR, Ross JS, Zhang W, Chau KH, Wayda B, Murugiah K, Lu DY, Mittal A, Krumholz HM. Publication and reporting of clinical trial results: Cross sectional analysis across academic medical centers. BMJ. 2016;352

Ranasinghe I, Shojaee A, Bikdeli B, Gupta A, **Chen R**, Ross JS, et al. Response to Letter Regarding Article, "Poorly Cited Articles in Peer-Reviewed Cardiovascular Journals from 1997 to 2007: Analysis of 5-Year Citation Rates". Circulation. 2016;133(2):e23-4.

**Chen R**, Strait KM, Dharmarajan K, Li S-X, Ranasinghe I, Martin J, Fazel R, Masoudi FA, Cooke CR, Nallamothu BK, Krumholz HM. Hospital variation in admission to intensive care units for patients with acute myocardial infarction. American Heart Journal. 2015;170:1161-1169

Ranasinghe I, Shojaee A, Bikdeli B, Gupta A, **Chen R**, Ross JS, Masoudi F, Spertus JA, Nallamothu BK, Krumholz HM. Poorly cited articles in peer-reviewed cardiovascular journals from 1997-2007: Analysis of 5-year citation rates. Circulation. 2015

**Chen RJ**, Flores G, Shetgiri R. African-American and Latino Parents’ Attitudes and Beliefs Regarding Adolescent Fighting and Its Prevention. Journal of Child and Family Studies 2015:1-9

Johnston LC, **Chen R**, Whitfill TM, Bruno CJ, Levit OL, Auerbach MA. Do you see what I see? A randomised pilot study to evaluate the effectiveness and efficiency of simulation-based training with videolaryngoscopy for neonatal intubation. BMJ Simulation and Technology Enhanced Learning. 2015;1(1):12-8

Dreyer R, Murugiah K, Nuti SV, Dharmarajan K, Chen SI, **Chen R**, Wayda B, Ranasinghe I. Most important outcomes research papers on stroke and transient ischemic attack. Circ Cardiovasc Qual Outcomes 2013; 7:191-204

**Chen R**, Mody PS, Gupta A, Bikdeli B, Dreyer R, Chen SI, Nuti S, Ranasinghe I. Most important outcomes research papers on body weight, obesity and cardiovascular outcomes. Circ Cardiovasc Qual Outcomes 2013; 6:e48-56.

Meller SM, Chen M, **Chen R**, Haeseler FD. Near-peer teaching in a required third-year clerkship. Yale J Biol Med 2013;86:583-9. 

Gupta A, Dharmarajan K, Dreyer R, Bikdeli B, **Chen R**, Kulkarni VT, Shi R, Shojaee A, Ranasinghe I. Most important outcomes research papers on device therapies for cardiomyopathies. Circ Cardiovasc Qual Outcomes 2013; 6:e36-47. 

**Chen R**, Dharmarajan K, Kulkarni VT, Punnanithinont N, Gupta A, Bikdeli B, Mody PS, Ranasinghe I. Most important outcomes research papers on hypertension. Circ Cardiovasc Qual Outcomes 2013;6:e26-35.

Bikdeli B, Ranasinghe I, **Chen R**, Gupta A, Lampropulos JF, Kulkarni VT, Mody PS, Dharmarajan K. Most important outcomes research papers on treatment of stable coronary artery disease. Circ Cardiovasc Qual Outcomes 2013;6:e17-25.

Lampropulos JF, Gupta A, Kulkarni VT, Mody P, **Chen R**, Bikdeli B, Dharmarajan K. Most important outcomes research papers on variation in cardiovascular disease. Circ Cardiovasc Qual Outcomes 2013; 6:e9-16.

Gupta A, Lampropulos JF, Bikdeli B, Mody P, **Chen R**, Kulkarni VT, Dharmarajan K. Most important outcomes research papers on cardiovascular disease in women. Circ Cardiovasc Qual Outcomes 2013;6:e1-7.

Lampropulos JF, Bikdeli B, Gupta A, Mody P, Kulkarni VT, **Chen R**, Dharmarajan K. Most important outcomes research papers on valvular heart disease. Circ Cardiovasc Qual Outcomes 2012;5:e95-e103.

### PRESENTATIONS & POSTERS
Natarajan K, Jiang X, Kalluri K, Pang C, Lee J, Liu C, Chen R, Ryan P. A Collaborative Approach to Phenotype Development: Framing Concept Set Discovery as a Machine Learning Problem. 2019 OHDSI Symposium. North Bethesda, MD, 2019.

Jiang X, Kalluri KS, Pang C, Chen K, Lee J, Liu C, Chen R, Ryan P, Natarajan K. Feature Engineering to Power Machine Learning Phenotype Development. 2019 OHDSI Symposium. North Bethesda, MD, 2019.

Belenkaya R, Gurley M, Reich C, Dymshyts D, Warner J, Miller R, Williams A, Chen R. OMOP CDM Oncology Module at Work. 2019 OHDSI Symposium. North Bethesda, MD, 2019.

Belenkaya R, Gurley M, Dymshyts D, Araujo S, Williams A, Chen R, Reich C. Standardized Observational Cancer Research using the OMOP CDM Oncology Module. Medinfo 2019. Lyon, France, 2019.

Chen R, Falconer T, Hripcsak G. Phenotyping and Validation of Oncologic Diagnoses and Treatments using the OMOP Common Data Model. AMIA 2019 Informatics Summit. San Francisco, CA, 2019.

Wang Q, Zou Y, Reps JM, Rijnbeek PR, Kostka KF, Steward HM, Seng CY, Voss EA, Williams A, Williams R, Van Zandt M, Chen R, Gao G, Falconer T, Jackson Mulgrave JN, Kasthurirathne N, Fernandez-Chas M, Vashisht R, Pfohl SR, Ryan PB, Reich C. Development and Validation of a Prognostic Model Predicting
Hemorrhagic Transformation in Acute Ischemic Stroke. European OHDSI Symposium 2019. Rotterdam, Netherlands. 2019

Chen R, Ryan P, Natarajan K, Falconer T, Reich CG, Vashisht R, Shah NH, Hripcsak G. Treatment Pathways in Patients with Cancer Using a Large-scale Observational Data Network. AMIA 2018 Annual Symposium. San Francisco, CA, 2018.

Belenkaya R, Campbell WS, Chen R, Gurley M, Huff SM, Randhawa G, Reich C, Rocca M. Panel: Data Standardization in Cancer: Challenges and Opportunities. AMIA 2018 Annual Symposium. San Francisco, CA, 2018.

Knoll C, Banda J, Rao G, Chen R, Swerdel J. Tutorial: OHDSI Cohort Definition and Phenotyping. 2018 OHDSI Symposium. North Bethesda, MD, 2018.

Chen R, Tyler J. STEMI Care in Saipan: lowering morbidity and mortality through optimal delivery of evidence-based therapy. CHCC Grand Rounds. Saipan, CNMI, 2017.

Chen R, Chau KH, Bikdeli B, Akram Y, Punnanithinont N, Ross JS, Krumholz HM. A changing landscape: contemporary characteristics of major cardiovascular trials. American Heart Association Scientific Sessions, Dallas, TX, 2013.

Shi R, Ranasinghe I, Gupta A, Bikdeli B, Chen R, Punnanithinont NT, Lampropulos JF, Ross JS, Krumholz HM. Uncited or poorly cited articles in the cardiovascular literature. Peer Review Congress, Chicago, IL, 2013.

Chen R, Strait KM, Dharmarajan K, Li SX, Ranasinghe I, Martin J, Fazel R, Masoudi FA, Cooke CR, Nallamothu BK, Krumholz HM. Hospital variation in admission to intensive care units for patients with acute myocardial infarction. Quality of Care and Outcomes Research Scientific Sessions “QCOR 2013,” Baltimore, MD, 2013.

Holt S, Connors G, Dunne D, Sankey C, Siddharthan T, Chen R, Garner M, Wang, H.  Workshop on Strategies for Teaching the Physical Exam.  Annual Meeting, Northeast Group on Educational Affairs, New York, NY, 2013.

Holt S, Connors G, Dunne D, Sankey C, Siddharthan T, Chen R, Garner M, Wang, H.  Workshop on Strategies for Teaching the Physical Exam.  Yale Medical Education Day, New Haven, CT, 2013.

Chen R. Biomedical research and effective paper writing. Cardiology Grand Rounds, Xiangya School of Medicine. Changsha, China, 2012.

Chen R, Shetgiri R, Tilitski J, Ryan S, Flores G. Break it up! Parental attitudes and beliefs on youth violence and its prevention. 2011 Pediatric Academic Societies and Asian Society for Pediatric Research “PAS 2011,” Denver, CO, 2011.
